/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.17.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;


#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions

namespace tutorial
{
  public static class tutorialConstants
  {
    /// <summary>
    /// Thrift also lets you define constants for use across languages. Complex
    /// types and structs are specified using JSON notation.
    /// </summary>
    public const int INT32CONSTANT = 9853;
    public static Dictionary<string, string> MAPCONSTANT = new Dictionary<string, string>();
    static tutorialConstants()
    {
      MAPCONSTANT["goodnight"] = "moon";
      MAPCONSTANT["hello"] = "world";
    }
  }
}
